apiVersion: v1
kind: Secret
metadata:
  name: {{ required "pullSecretName is required" .Values.pullSecretName }}
  labels:
{{ include "ecr-pull-secret-refresh.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{}}'
