apiVersion: v1
kind: Secret
metadata:
  name: {{ required "pullSecretName is required" .Values.pullSecretName }}
  labels:
{{ include "ecr-pull-secret-refresh.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{}}'
{{- if .Values.snapshotRegistry.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "snapshotRegistry.secretName is required when snapshotRegistry.enabled=true" .Values.snapshotRegistry.secretName }}
  labels:
{{ include "ecr-pull-secret-refresh.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{}}'
{{- end }}
