apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-pull-secret-refresh.name" . }}
  labels:
{{ include "ecr-pull-secret-refresh.labels" . | indent 4 }}
automountServiceAccountToken: true
